### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by scopatz** [arizonat/py-stl-toolkit#1]
Hello @arizonat. How is this software licensed?

**Comment by arizonat** [comment]
To be honest I haven't thought much about it. I think I'd like this to be as open as possible. I think MIT seems suitable for that, what purposes are you interested in? I'll go ahead and make it as such unless you think it should be otherwise.

**Comment by scopatz** [comment]
Hi! MIT sounds great.  I was thinking to use this for Antimony -> STL -> Embree.

**Comment by arizonat** [comment]
Awesome, looks cool!

As a warning, I haven't really looked at this code in a long time, but would be happy to help out as needed. I'll mark this issue as closed though. Hope you find it useful :)

**Comment by scopatz** [comment]
Thanks @arizonat!
